### ISSUE TITLE
Diplay value of total country electricity supply (GW) and GHG emissions (ktCO2eq/h)

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#101]
Would be nice to display as text somewhere, at the mouse pointer when flying over a country or in the left box when clicking on a country, the total country GHG emissions from electricity (in ktCO2eq/h) and total electricity production (in GW)

**Comment by corradio** [comment]
Makes sense. It avoids looking for the co2eq number on the scale or in the panel.

**Comment by corradio** [comment]
@brunolajoie I think showing total emissions and total production might just clutter the view.
Also, we never talk about total emissions / production because it's hard to compare and get a sense of intuitively. I feel like it's only relevant for quant-oriented people, so I'd be against doing it. Do you agree?

**Comment by brunolajoie** [comment]
all right
