### ISSUE TITLE
Change map title to remove "Climate impact"

### ISSUE THREAD

**Issue by parisenbouteille** [corradio/electricitymap#107]
Change to "Real-time GHG emissions intensity of the European electricity production", or something approaching.

**Comment by corradio** [comment]
@brunolajoie suggested "greenhouse gas emission intensity" but I feel like it's a bit more heavy and less "user-friendly" (plus it's in the subtitle).
What is your rationale for changing? Is it because it's not precise enough (and we might get criticised)? To me there's a general consensus that CO2eq is reflecting the climate impact. We could instead quantify the climate forcing induced by the amount of CO2eq measured, but that seems overkill to me?
