### ISSUE TITLE
Show electricity storage in country panel

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#118]
We are able to know, for example with RTE (FR), that they are storing energy in their pumped hydro storage. We could show this in the panel.
Concretely, it shows up as negative production, and we currently filter out those and only show positive.

**Comment by corradio** [comment]
I'd like to re-prioritise this. It would be nice to see "negative" production when hydro plants pump energy uphill, cc @brunolajoie 

Right now, we sum all types of hydro, and some count as a negative contribution (when one type is consuming rather than producing). The sum of all is put in the "hydro" line in the EM.
Instead, we should probably isolate the part that can be negative, and in our CO2 model, ignore the negative part (else it would "absorb" CO2).

We have the data for ENTSOE

![image](https://cloud.githubusercontent.com/assets/1655848/22364485/317520fe-e472-11e6-9b58-2ff87059ebca.png)

What do you think @brunolajoie @ThierryOllivero ? This would mean having "hydro" (always > 0) and "hydro (pumped) storage" (which can be < 0)

**Comment by brunolajoie** [comment]
This is an interesting point. 

- At the moment LCA emissions data we use are per kWh of electricity _produced_, because it refers to i think normal damn powerplant without pumped storage capacities. I will double check. So, if we net it from electricity stored in reservoirs, we are actually diminishing total CO2 emissions, so its not ideal. --> **We should therefore change our code to only use kWh produced to calculate the CO2**

- Now, what do we want to display on the left country panel on the map? The electricity _produced_ per type of power plant, or the net electricity produced minus consummed at each power plant? To answer this, let's look at other types of power plant like nuclear: They also consumed tens of MW of power. Does ENTSOE provides the NET output or the positive output of the plant? **I think we should align to the other types of power plant**

**Comment by corradio** [comment]
For the first point: it's already done like that.

**Comment by corradio** [comment]
I was thinking about something like that:

![image](https://cloud.githubusercontent.com/assets/1655848/22395804/d5a37276-e548-11e6-99ea-fdcf12c31944.png)

We can either show pumped hydro (which can either be >0 or <0), or we can show specifically storage (which is always <0) in opposition to hydro production (always >0).
