### ISSUE TITLE
Support multiple data sources for each country

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#131]
ENTSOE data is difficult to rely on. Sometimes it is heavily delayed, and sometimes it stops working.
We have other parsers (i.e. FR, CZ) that could do the job in case ENTSOE stops working.
The biggest problem here is data consistency if we have two or more sources.

**Comment by Pantkowsky** [comment]
I would say that we should have some scripts put aside that the main script responsible for populating the map with data would call in case no data was provided by entsoe. I think we should aggregate the secondary sources of information and create parsers for them, implemented iteratively. Then, when clicking on a country, there should be a place referencing a source (so in case that the secondary parser gets called, because entsoe did not provide data, the user would see the proper source). The purpose would be to not mislead the user in a case that he thinks that the current data is from entsoe, where in fact its the secondary script running with data from some other place. By doing so, there would be a plan B in case entsoe crashes, or stops providing any information.

**Comment by corradio** [comment]
Let's assume two parsers are written for a country.
They both run all the time, so we end up having two timeseries of data (one for each source) in the database.
We can chose to always show the last one. However, for a majority of cases, ENTSOE will be more delayed than the custom parser (~1-6hours) but will have most of the production modes whereas the custom parser will only have a couple. Simply picking the last data regardless of the source is maybe not the best strategy. We need something better.
But maybe starting with picking the last one is enough for now?

**Comment by Pantkowsky** [comment]
Why would they have to run all the time? Couldn't there be the main one running all the time and in case he returns no data, then the second one runs? Then after x hours repeat the step to see if the main parser is back at returning data, if so, display this and turn off the second parser, if not then continue with second parser.

**Comment by corradio** [comment]
There's several challenges with this. First, when do you decide that the
main parser return no data? After 24h of no data? Then it means we have to
wait 24h to switch parser.
Second, de-activating the main parser, and re-checking each x hours require
to store the information that the main parser did run y hours ago, and
failed/succeeded. It adds complexity because we need to store that
information in a database, and it includes edge cases.
I prefer the approach where we store all the data we can (multiple parsers
for the same country), and then we use a rule to express our preferences to
select between different data sources when a user fetches the data.

**Comment by corradio** [comment]
For reference, if this is fixed, then we can merge this: https://github.com/corradio/electricitymap/pull/128

**Comment by Pantkowsky** [comment]
Portugal and Estonia are missing for a couple of days now.
