### ISSUE TITLE
Missing Flag for Kosovo

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#163]
![image](https://cloud.githubusercontent.com/assets/22315693/21128951/02ce91f4-c0ff-11e6-9de8-c9baec8b54a7.png)

**Comment by ThierryOllivero** [comment]
The problem comes from the absence of a XK.svg flag in the flags folder. We can make ones.

@corradio: What are the specs for flags? Is it ok to add a flag manually in the folder?

**Comment by corradio** [comment]
Flags come from here: https://github.com/lipis/flag-icon-css
Maybe they already have Kosovo? Else we can ask them?

**Comment by GergelyMindler** [comment]
There are no flag for XK.

**Comment by GergelyMindler** [comment]
It needs to create.

**Comment by corradio** [comment]
Maybe we should show a generic "no flag" flag?

**Comment by GergelyMindler** [comment]
@corradio Good idea, but lipis does not support no-flag flag here: https://github.com/lipis/flag-icon-css

We have to create it.

**Comment by GergelyMindler** [comment]
I created a sample no-flag flag in both version (1x1, 4x3). If this is good, pls add to folder with name "no-flag.svg" - I had to use custome name because of github limitations. But it is in picture:
[no_flag_1x1.svg.txt](https://github.com/corradio/electricitymap/files/692803/no_flag_1x1.svg.txt)
[no_flag_4x3.svg.txt](https://github.com/corradio/electricitymap/files/692804/no_flag_4x3.svg.txt)

![image](https://cloud.githubusercontent.com/assets/24973489/21758455/3674d2dc-d63c-11e6-8e83-394785ca3cfc.png)

**Comment by corradio** [comment]
Cool @GergelyMindler ! It would be easier for me if you submit a full pull request with the feature! Do you have experience with javascript?

**Comment by GergelyMindler** [comment]
Well, these flags were only xml - that is not a big task.

Otherwise, i did a few things in javascript. Not every thing but this task seems be relativelly easy. I am able to solve it but till I cannot start the project locally for testing, I do not want to change so deep the source code...

Till then I upload just the np-flag flags.

**Comment by corradio** [comment]
Not applicable anymore
