### ISSUE TITLE
Display emission intensities per capita

### ISSUE THREAD

**Issue by pirg** [corradio/electricitymap#169]
You designed a great tool, thanks !
I was wondering if a different way of presenting the data could be shown, gCO2eq/capita/h and W/capita. Take Italy and France with similar population 6e7 people. Right now, France and Italy are both emiting ~4ktCO2eq/h mostly because of gas plants. But because France's overall consumption is so large (75GW against ~12GW for Italy), when looking at gCO2eq/kWh it looks like France is not emiting a lot of CO2 although it's emiting in absolute term (and per capita) as much as Italy.

**Comment by ThierryOllivero** [comment]
Hello Pierre ( @pirg ) ! 

Thanks for your feedback. We had discussed this point in issue number #101 , I'll let you have a look if you want. It's hard to find a nice way to show it, but you're totally right, CO2eq/kWh is not enough and we could improve it.

Regarding Italy and its 12 GW, we might have an issue here. They probably produce much more than that, but the data are not transferred to the Transparency Platform. This is why we kept #72 open. 

Either way, thanks again for your feedback and your nice comment about the map.

**Comment by corradio** [comment]
Thanks Pierre for the inputs!
I think adding emissions per capita makes sense. We need to find a proper way to put it in the design though, so it doesn't become confusing. If anyone has ideas, feel free to put them here!

**Comment by kilotaras** [comment]
I would suggest a simple switch that will change display units and update colors accordingly.

**Comment by corradio** [comment]
Just to be clear about my thoughts: dividing by capita blurs the picture, because for example a country that has few inhabitants but has a lot of factories will appear high on co2/cap. So you can "trick" the numbers by moving your factory abroad and import the produced good instead of the electricity. Then you suddenly have a low co2/cap number because we only count CO2 for electricity (not for imported/exported goods). CO2 intensity on the other hand doesn't depend on that. It doesn't care about the electricity is used for.
