### ISSUE TITLE
Arrow animations are CPU intensive

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#199]
Deleting the arrows significantly increase the framerate of the wind field.
Check maybe `d3.active` in https://github.com/d3/d3/blob/master/CHANGES.md#transitions-d3-transition

**Comment by corradio** [comment]
@scarlac will look into this (thanks!!)

**Comment by corradio** [comment]
Seems like even CSS transitions are slow on non-SVG elements.
We're looking into a way to add an animated GIF on top of (non-animated) arrows.

**Comment by scarlac** [comment]
For anyone interested: (Looping) Animations in SVG are very CPU intensive. This is both the case for SVG animations as well as SVG with CSS animations. Tried removing the gradient, using static images instead of linear-gradient, placing animations in separate <svg> but nothing worked. Having just a few would be okay but we have ~50 arrows so our solution was to generate GIF images using imagemagick and place them inside the SVG. This works quite well and only have a few downsides.

**Comment by nikkozzblu** [comment]
Icons set is definetly the way to go. Nice job Seph !!

Nico Juguet

-------- Mensaje original --------
Asunto: Re: [corradio/electricitymap] Arrow animations are CPU intensive (#199)
De: Seph Soliman
Para: corradio/electricitymap
CC: Subscribed


For anyone interested: (Looping) Animations in SVG are very CPU intensive. This is both the case for SVG animations as well as SVG with CSS animations. Tried removing the gradient, using static images instead of linear-gradient, placing animations in separate but nothing worked. Having just a few would be okay but we have ~50 arrows so our solution was to generate GIF images using imagemagick and place them inside the SVG. This works quite well and only have a few downsides.
