### ISSUE TITLE
Disable iframe embedding

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#236]

**Comment by ThierryOllivero** [comment]
Could use something like:

`<script type="text/javascript">
function noiFrame() {
try {
if (window.top !== window.self) {
document.write = "";
window.top.location = window.self.location;
setTimeout(function() {
document.body.innerHTML = '';
}, 0);
window.self.onload = function() {
document.body.innerHTML = '';
};
}
} catch (err) {
}
}
noiFrame();
</script>`

For us to decide what we show if "document.body.innerHTML" instead of an empty page. 

Maybe a message saying "Embedding of the ElectricityMap has been deactivated. Please contact us at hello@tmrow.co" or something like that.

**Comment by corradio** [comment]
Yes. We should show a link to the EM too.

**Comment by corradio** [comment]
Fixed by https://github.com/corradio/electricitymap/commit/29b05c5050d5f35a843af7907acc415b11e86b13
