### ISSUE TITLE
Add all power plants on the map and their real-time production

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#238]
Would be nice to add all power plant on the map, with a button to display/hide them at will.

ENTSOE dataset is readily available here https://transparency.entsoe.eu/generation/r2/actualGenerationPerGenerationUnit/show

**Comment by corradio** [comment]
@tobiasseidel did some work already here:
http://nbviewer.jupyter.org/github/tobiasseidel/electricitymap/blob/master/datascience/OSM.ipynb#Bokeh-plot-of-all-power-plants-in-europe-mapped-in-OSM

From a product design perspective, why would someone want to see all power plants? Is it to get a feeling of how big the capacity is for each type of production in each country? Is it to get to a higher spatial granularity?
Another thought: it might be a good idea to have this as a second map instead of overlaying with this one.

**Comment by corradio** [comment]
@brunolajoie I'm closing this because the map will have too much information else.
Please re-open if you don't agree!
