### ISSUE TITLE
Interpretation of electricity map

### ISSUE THREAD

**Issue by KimVM** [corradio/electricitymap#259]
Dear, thanks for the interesting and interactive website.
I wanted to verify whether I am interpreting the data correctly (I am taking the example of Belgium):

Is it correct to state that, based on the shown data:
- Belgium currently  produces 603 MW of electricity from renewables and has the potential to produce 7.41 GW from renewables?

- What is the reason that no electricity production from solar/hydro is mentioned for Belgium?

Thanks for the informative website,
looking forward to your answers,

wbr
Kim
[electricity production Belgium.xlsx](https://github.com/corradio/electricitymap/files/698157/electricity.production.Belgium.xlsx)

**Comment by ThierryOllivero** [comment]
Hello KimVM,

Your interpretation is right.

Please note that the map currently shows data from 11 hours ago, because Belgium did not transmit more recent data yet. 11 hours ago, it was night in Belgium, therefore... no solar electricity. For the Hydro, I don't know. 

If you look at the data from yesterday noon, you find the following: 

![image](https://cloud.githubusercontent.com/assets/22315693/21840154/375352cc-d7dc-11e6-8055-5de0305a2714.png)

A little bit of sun, a little bit of wind and a little bit of hydro.

Hope it helps, I will close the issue because it is not something we should work on, but we can continue the discussion if you want.

Best regards,

Thierry
