### ISSUE TITLE
Investigate & document oil emission intensity

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#278]

**Comment by ThierryOllivero** [comment]
Feedback on Twitter : 

@tmrowco Estonia uses oil shale to generate electricity, not oil. Oil shale is much more CO2 intensive than oil, more akin to tar sands.

**Comment by ThierryOllivero** [comment]
Bruno: you can give a look at issue #294 for Estonia.

**Comment by alixunderplatz** [comment]
I did some research on the Estonian electricity production from oil shale, too.
According to a German paper from 2009, this may result in extreme emissions of about 1600 g CO2/kWh. I guess the numbers that are currently used are for combustion of heavy oil or light heating oil.

I have found this number for oil shale in a German report, p. 38:
https://www.bee-ev.de/fileadmin/Publikationen/Studien/091123_era-Studie_Marginal_Oil_Endbericht.pdf

> "Die Ölschiefernutzung zur Stromerzeugung in Estland belegt die Probleme des hohen
Carbonatabbaus. Im Vergleich mit Strom aus Kohle führt die heutige Schieferverbrennung in
Estland zu 60 % höheren CO2-Emissionen (1.600 g CO2eq/kWh)109. Die Ölschieferverarbeitung
führt aber auch mit modernsten Technologien zu Emissionen, die bis zu 75 % höher als bei
konventionellem Erdöl sind."

which translates to:

> The use of oil shale for electricity production in Estonia proves the high ratio of carbonate break down. In comparison to coal combustion, today's oil shale combustion leads to 60% higher carbon dioxide emissions (1600 g/kWh). Shale oil processing leads to emissions which are 75% higher than for conventional crude oil, even with modern technologies.

The shale which contains the oil is pulverized and then fed into the combustion chamber. The high emissions are caused by the combustion temperature (700-1100°C), which partially decomposes the carbonates of the shale material in a chemical reaction and creates CO2. 

I'm trying to find some infos on yearly electricity production and carbon dioxide emissions. I'll give you an update. 
Seems like you need to find a color blacker than black if this is confirmed!

**Comment by greennuts** [comment]
1600g/kWh is nearly close to what I calculated in https://github.com/corradio/electricitymap/issues/294 from this study http://www.easac.eu/fileadmin/PDF_s/reports_statements/Study.pdf
So I don't think it will get greener. Sorry Estonia, you are the new black hole in Europe :)

**Comment by brunolajoie** [comment]
Thanks a lot guys,

So, if i may summarize what we have: 

- 1600gCO2eq/kWh electric, reduced to 1000 with new boiler, with LCA analysis from EASAC "A study on the EU oil shale industry – viewed in the light of the Estonian experience", 

- 1300gCO2/kWh (CO2 only, no LCA) for old boiler, 1050 for new boilers 
(source: TTU LCA of the Estonian Oil Shale Industry, page 46)

- 1100gCO2/kWh for CO2 only, non-LCA analysis quoted in IEA (2013) "Estonia Energy Report"

There are 3 oil shale power plant at the moment
Eesti Elektrijaam	1369MW (old boilers, except 1 out of 14), n°10 most polluting EU power plant
Balti Eleketrijaam	472MW (old bioler, except 1 out of 20+)
Auvere 270MW	270 (new boiler type, built by alstom in 2014) #gromert

So, its approximately 15% new boiler. 

To conclude, I would favor using the figure of 85%*1600 + 15%*1000 = 1515gCO2eq/kWh for our EM.
