### ISSUE TITLE
One small bug and an idea for improvement

### ISSUE THREAD

**Issue by snsstrimer** [corradio/electricitymap#299]
Hello,
Don't need to say how much I enjoy this project. It is very inventive and neatly written.
Unfortunately, when I was checking informations about electricity production in Poland I noticed, that the upper amount of installed coal capacity does not fit the chart's bar. The same is with hydro in Sweden and solar in Italy.
And about an improvement:
I think, that possibility to hide the menu to see a whole map would be a nice actualisation.
Take it easy ;)
![bug](https://cloud.githubusercontent.com/assets/20342117/22037481/93725010-dcf7-11e6-8595-7cf0727395e2.png)

**Comment by ThierryOllivero** [comment]
Hello @snsstrimer and many thanks for your nice feedback. 

We know the problem, it comes from here: 

![image](https://cloud.githubusercontent.com/assets/22315693/22037622/35e71f42-dcf8-11e6-9517-f69a34d68948.png)

We already had the issue #235 on that. 

@corradio, you had fixed it with a commit, but the problem is still there. I'll let you give a look when you have time?

@snsstrimer : regarding to your idea, you want to completely get rid of the menu on the left, is that so? 

Thanks!

**Comment by snsstrimer** [comment]
@ThierryOllivero : Copy that! ;) Going back to the idea: no, not "completely get rid of it", but put a button that rolls it up and down again. Then this action would be only temporary.

**Comment by snsstrimer** [comment]
Ok, so you have fixed Poland chart, but there are still problems with Italy and Sweden charts.
![bug_italy](https://cloud.githubusercontent.com/assets/20342117/22087988/7403c0fc-dde1-11e6-8e94-ca915e38c5c3.png)
![bug_sweden](https://cloud.githubusercontent.com/assets/20342117/22087995/78d7b836-dde1-11e6-982c-7ac3824adb1d.png)
Take your time ;)
