### ISSUE TITLE
Prices - "Electricity Spot Price" not precise enough

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#310]
Hello @corradio and @nikkozzblu,

Thanks for your work on prices. Love it. A little issue though.

The map currently shows "Electricity spot price", which is not defined.

It seems like we are currently recovering A44 from ENTSO-E Transparency Platform. Unless I'm mistaken, A44 consists of "Day-Ahead" prices. Not "Intraday".

Therefore, I would suggest to:
- Either fetch Intraday prices somewhere
- Rename "Electricity Spot Price" into "Day-Ahead Price".

Also, please update the Readme.MD to explain where the prices are coming from (and that we are talking of Day Ahead).

Best regards,

Thierry

**Comment by nikkozzblu** [comment]
Hello,

Almost raised that one as well, actually in my version I used day-ahead.
Then found that EPEX actually refer to SPOT prices as Day-ahead
https://www.epexspot.com/en/market-data/elix
hence let it go.
But in any case "Day-Ahead" I definetly more precise and "Intraday" can come after

**Comment by corradio** [comment]
We should definitely update the README. However the main question is whether or not "spot prices" is better than "day ahead prices". I think day ahead prices induces more complexity, because it forces you to understand there's a market where people bid 24h ahead of time etc..
There I settled on "spot prices", which is easy to understand from a non-expert point of view: it's the price of electricity on the spot market, regardless of how that spot-market works.

However, when/if we add the intraday (balancing) prices, we will need to make a very clear distinction. For now I personally believe it's ok?

**Comment by nikkozzblu** [comment]
I still vote for day ahead, intraday (or 2 hours ahead) is another, and balancing (with 3 levels!¡!) yet another ones.
Yes electricity market are not simple :p

**Comment by corradio** [comment]
Please re-open if the fix is not good enough:

![image](https://cloud.githubusercontent.com/assets/1655848/22240164/221c5c62-e21a-11e6-817e-8685fe0b3602.png)

Readme was also updated.

**Comment by ThierryOllivero** [comment]
Looks good to me !
