### ISSUE TITLE
GB-NIR etc 

### ISSUE THREAD

**Issue by guynicholson** [corradio/electricitymap#318]
Hi really great web site.
1) Northern Ireland is labelled GB-NIR.  Northern Ireland is part of UK (as is GB) therefore either label
           UK-GB and UK-NIR 
                       or
           GB and NIR
     You could use NI instead of NIR.
2) there is no nuclear generation in NIR.
3) the popup text box on the  flow form Norway to Finland  is not visible (off the top of the screen).
4) could you show the capability and % as well as the flows on the cross border flows? e.g. GB-NL is 1000MW.  http://www.britned.com/.  I appreciate this is much easier for single HVDC connections compared to multiple AC connections across borders, but would be useful even in limited to HVDC.
5) the "unknown" tab in GB is I believe biomass (mainly from Drax powerstation part converted from coal) but is shown as "other" in BM reports.
https://www.theguardian.com/environment/2016/dec/19/power-station-shares-jump-ec-approves-wood-burning-subsidies-coal-switch
http://www.drax.com/
https://www2.bmreports.com/bmrs/

Good work!  Regards Guy

**Comment by corradio** [comment]
Hello @guynicholson ,

1. GB-NIR is actually the ISO 3166 code for the "subunit", even though Northern Ireland is part of UK https://en.wikipedia.org/wiki/ISO_3166-2:GB. It's an attempt to slowly move to "zones" instead of "countries".
2. Thanks! @brunolajoie or @ThierryOllivero can one of you guys take a look at GB-NIR capacities?
3. Good catch! I'm fixing this right away.
4. I'm adding an issue for that: #319
5. We're getting our data from ENTSOE. Maybe that's a feedback for @rustyb, who's our contact there.

**Comment by ThierryOllivero** [comment]
@corradio right now we have no capacities for GB-NIR in the file. 

On ENTSOE, we have information for UK and for Ireland, but no split for NIR. 

@brunolajoie any idea?

**Comment by brunolajoie** [comment]
NIR Capacity (2016) 
Source: http://www.eirgridgroup.com/site-files/library/EirGrid/Generation_Capacity_Statement_20162025_FINAL.pdf

Wind: 863MW
Sun: 77M
Gas: 1004MW
Oil: 415MW
Coal: 764MW
Biomass: 35MW

Interconnector: 450MW 

I'll create a pull request with these modifs

**Comment by ThierryOllivero** [comment]
Question: these capacities are today reported in UK on ENTSO-E. Should we remove them from GB capacities?

**Comment by corradio** [comment]
Let's discuss on https://github.com/corradio/electricitymap/issues/323#issuecomment-275450749
