### ISSUE TITLE
Can't click through to individual country in Safari on OS X

### ISSUE THREAD

**Issue by scottlee120** [corradio/electricitymap#48]
I just get the beachball and nothing happens - computer lags until I close the tab. :(

**Comment by corradio** [comment]
Discussed with @scottlee120. What about we disable the viz for Safari and only enable for Chrome? WDYT @guicoelho

**Comment by guicoelho** [comment]
Hmm, I think that even if it doesn't work 100% well in all browsers, it
still delivers something for those Users. If nothing else, it shows that
they could see a great viz if only they had the right browser. What we
could do instead is displaying a warning overlay to everyone who's not
acessing from Chrome Desktop, saying that they should switch to Chrome for
a better experience, but still giving them the chance to "continue anyway".



Am Freitag, 9. September 2016 schrieb Olivier Corradi :

**Comment by corradio** [comment]
Just to make sure we're on the same page: on Safari it's almost unusable because of the delays.
So in this case I think it delivers almost nothing. Do you think you can test on your Mac and tell us how it feels?

**Comment by guicoelho** [comment]
I just tested it. And you're right, it's unusable. The mouse cursor stays forever "loading" as if the browser is permanently making a huge effort to render the thing. I also vote for completely preventing anyone who's not on Chrome Desktop from seeing it... it brings more harm than good this way. 👍

**Comment by guicoelho** [comment]
It could simply look like this:

![bummer](https://cloud.githubusercontent.com/assets/4061341/18396796/a9ceb440-76c5-11e6-9109-edcbac175e87.png)

**Comment by corradio** [comment]
That's niiiiice! Two points:
- I'd remove the "R" (registered) mark
- I'd say "switch to Chrome" instead of "install Chrome" (it sounds less "sponsored".

I've got to say, you're one fast prototyper!

**Comment by guicoelho** [comment]
Nice!

Regarding the R I just thought it's mandatory to have it there. But we can
just ignore it... Fine for me.

Regarding the call to action, I have some reserves about "Switch to"
because that's not what happens when you click the button (assuming we're
linking to the download page)... So it's a bit misterious what's gonna
happen when I click "switch". As an alternative we could maybe also write
"Download Chrome"... Because that also represents well what's actually
gonna happen 😉

Cheers



Am Freitag, 9. September 2016 schrieb Olivier Corradi :

**Comment by corradio** [comment]
..which directs us to the question: how many users do have Chrome already installed?
I was assuming almost everyone has (but doesn't necessarily use it). If that's the case, then we should probably remove the download button and have a "switch" message.
If it's not the case, then indeed downloading is ok.

In both cases I think that if we just add a message like "To view this [...], please switch to Chrome. You can install it here if you don't already have it:".

**Comment by scottlee120** [comment]
http://www.w3schools.com/browsers/browsers_stats.asp

Realistically, I think between Chrome and Firefox, we have most bases covered ;)

**Comment by guicoelho** [comment]
Yeah, there will definitely be both cases: people who have chrome and
people who have to install it.

The ones who have it will quickly realise they have to switch and do it.
The ones who don't have it, and potentially don't even know what it is,
need a big button - a clear next step - otherwise they'll close EM and
never come back.

I agree we should adapt the copy more towards "please switch to chrome in
order to view this. If you don't have chrome, you can install it here: <big
button>".

Makes sense?

Am Samstag, 10. September 2016 schrieb scottlee120 :

**Comment by corradio** [comment]
Cool! Can you make the changes? If yes, I'll give you access to the repo so you can make a feature branch instead of working on your fork

**Comment by guicoelho** [comment]
Sure - I'll take care of this tomorrow. Working on the research page design now

 





On Sat, Sep 10, 2016 1:51 PM, Olivier Corradi notifications@github.com
wrote:
Cool! Can you make the changes? If yes, I'll give you access to the repo so you
can make a feature branch instead of working on your fork
