### ISSUE TITLE
Update DK breakdown with ENTSOE data

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#81]
Entsoe has data about the breakdown of the danish electricity production.
Maybe we should consider using their api.
[link](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=26.09.2016+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=26.09.2016+00:00|CET|DAYTIMERANGE&area.values=CTY|10Y1001A1001A65H!BZN|10YDK-2--------M&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+%28UTC+1%29+/+CEST+%28UTC+2%29)

**Comment by ThierryOllivero** [comment]
Pros of using their API: Actual and "official" data, for all countries in Europe.
Cons of using their API: All data would come from the same source. No more need for Parsers. XML. 

In the end, if we decide to go with their API, we have to go further than only "dataviz". Explain the color. The figures. Educate the viewer.

I'd like that.

**Comment by corradio** [comment]
If we use their api our added value is basically the co2 model and the visualisation.
It would be great to dig a bit more into the API and quickly figure out what the coverage is, how reliable the data is etc..

**Comment by ThierryOllivero** [comment]
For the coverage and reliability, I would say "EU28" and "reliable", because:

​Transparency has improved markedly in Europe over the past few years, culminating in  Regulation (EU) No 5 43/2013 of 14 June 2013 on submission and publication of data in electricity markets. Through this Regulation, **it has now become mandatory for European Member State data providers and owners to submit fundamental information related to electricity generation, load, transmission and balancing for publication through the ENTSO-E Transparency Platform.** 

https://www.entsoe.eu/data/entso-e-transparency-platform/Pages/default.aspx

**Comment by corradio** [comment]
The real problem here is that ENTSOE only has hourly data for DK.
We could however use a heuristic to break the real-time data down based on the hourly data.
